# Generated by Django 4.1.1 on 2023-01-21 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['id'], 'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
    ]
