# Generated by Django 4.1.1 on 2023-01-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_alter_loan_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reader',
            old_name='natinality',
            new_name='nationality',
        ),
        migrations.AlterField(
            model_name='reader',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
