# Generated by Django 4.1.1 on 2023-01-21 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_remove_author_edad_mayor_18_author_edad_mayor_18'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='names',
        ),
    ]
